### ISSUE TITLE
mount smb folder

### ISSUE THREAD

**Issue by lpt2007** [pierrickrouxel/hassio-addon-transmission#10]
Can I mount smb folder to /share/downloads? How?

thx in advance for answer

**Comment by sesapriv** [comment]
I would also like this option

**Comment by aaamoeder** [comment]
Use the standard SMB addon (https://github.com/home-assistant/hassio-addons/tree/master/samba)
Then set the download path in transmission to "/config/downloads"

**Comment by pierrickrouxel** [comment]
Thank you @aaamoeder for your answer.
