### ISSUE TITLE
Possibility to set incomplete foder

### ISSUE THREAD

**Issue by michelebossa** [pierrickrouxel/hassio-addon-transmission#12]
Hi i'd like if it is possible to change the default incomplete folder at moment it is setted with \share\incomplete.

Maybe something into config section of addon.

Thanks.

**Comment by pixeldublu** [comment]
@michelebossa See latest version. You can now set incomplete and download folder from config. 🙌

**Comment by michelebossa** [comment]
Thanks

**Comment by michelebossa** [comment]
Hi @pierrickrouxel,
I have tried to install but i recive an permission error under alpine repository

![image](https://user-images.githubusercontent.com/38975058/134647272-ed3ba0cb-cad6-4c00-bd87-1e325331908d.png)

i suppose the solution it will be to add RUN sed -i 's/https/http/' /etc/apk/repositories into dockerfile begin of RUN apk add --no-cache \ it is possible to add thse instruction?

Issue on apline git.
https://github.com/alpinelinux/docker-alpine/issues/98

Thanks

**Comment by michelebossa** [comment]
Just an update for all guy in my situation it is a problem my side fixed by these commands:
![image](https://user-images.githubusercontent.com/38975058/134866591-677b8079-8788-4210-857e-83d9ecea5066.png)
url https://community.home-assistant.io/t/supervisor-cant-install-add-ons/301771/15
