### ISSUE TITLE
"Command not found" errors when enabling openvpn

### ISSUE THREAD

**Issue by pjrt** [pierrickrouxel/hassio-addon-transmission#18]
I enabled openvpn, using a nordvpn ovpn file. When I do that, I get the following errors:

```
/var/run/s6/etc/cont-init.d/10-requirements.sh: line 27: bashio::config.get: command not found
/var/run/s6/etc/cont-init.d/10-requirements.sh: line 27: bashio::file_exists: command not found
/var/run/s6/etc/cont-init.d/10-requirements.sh: line 28: bashio::config.get: command not found
/var/run/s6/etc/cont-init.d/10-requirements.sh: line 28: bashio::die: command not found
[cont-init.d] 10-requirements.sh: exited 127.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
```

And then the addon stops. 

I placed the ovpn file in the `/config/opevpn/` directory can called it by file name, not path.

**Comment by pjrt** [comment]
I googled bashio and it seems to be another addon. Is that addon a requirement for this one?

**Comment by pjrt** [comment]
I googled some more and it seems bashio isn't just an addon, it is a dependency added to home assistant installation. I'm not that familiar with Add On development so not really sure what the issue is.

**Comment by alexbelgium** [comment]
Hi,

You're using "#!/usr/bin/with-contenv bashio" but haven't installed it.
To install it, you need to add this code (or an equivalent) to your DOCKERFILE : 
```
ARG BASHIO_VERSION=0.13.0
# Install bashio
RUN  mkdir -p /tmp/bashio \
    && curl -L -f -s "https://github.com/hassio-addons/bashio/archive/v${BASHIO_VERSION}.tar.gz" \
        | tar -xzf - --strip 1 -C /tmp/bashio \
    && mv /tmp/bashio/lib /usr/lib/bashio \
    && ln -s /usr/lib/bashio/bashio /usr/bin/bashio \
    && rm -rf /tmp/bashio
```
However it should had been enabled by default in the upstream image hassioaddons/base-aarch64:8.0.1

**Comment by aLTeReGo-SWI** [comment]
I have the same issue, but I'm not running HASSOS. I'm running Home Assistant supervised on Ubuntu. Adding that to the DOCKERFILE either did not work, caused the container to fail to load, or disappeared shortly after adding it. Why is this add-on dependant upon Bashio?
