### ISSUE TITLE
Add-on doesn't run

### ISSUE THREAD

**Issue by y0ast** [pierrickrouxel/hassio-addon-transmission#3]
Currently the add-on doesn't build, I fixed that by updating coreutils: https://github.com/y0ast/hassio-addon-transmission/commit/adabdcfa1e5d991679bd079e1b5be67120ad4749

However now when attempting to run the add-on it gives: 

```
[FATAL tini (6)] exec /usr/bin/run.sh failed: No such file or directory
```

I've tried running it locally too using docker but get similar:
```
standard_init_linux.go:207: exec user process caused "no such file or directory"
```

Do you have any idea for a fix?

**Comment by postlund** [comment]
I just submitted a PR (#4) that adds support for ingress (as well as doing som general maintenance) which should fix this. Hopefully @pierrickrouxel can have a look at that and maybe merge it.

**Comment by pierrickrouxel** [comment]
Thank you @postlund. I close this issue. Feel free to reopen it if it doesn’t work after update.
